name: Publish Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build 🔧 # This is built using npm and outputs the result to the 'build' folder.
        run: |
          npm install
          npm install -g parcel
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
